### ISSUE TITLE
CFC: Issues #3, #6, and #7 - sync vs. async

### ISSUE THREAD

**Issue by jernoble** [w3c/autoplay#11]
[Media WG Chair hat on]

This is a Call for Consensus on the question raised in issues #3, #6, and #7: Should the Autoplay Detection APIs be synchronous and therefore simple attributes, or should they be asynchronous and therefore methods which return Promise<> objects.

The arguments presented for a synchronous vs. asynchronous API are as follows:

Synchronous:
* Easier to use for web authors.
* Autoplay restrictions are currently implemented as synchronous for every major browser.

Asynchronous:
* Allows implementors to make performance optimizations by delaying costly operations until the first time autoplay is requested, implicitly or explicitly.

This question has been extensively discussed both in GitHub issues, in a face-to-face meeting after FOMS 2018 NY, and most recently at the Media WG F2F at TPAC 2019. At the most recent F2F, there was broad–but not unanimous–agreement in the room that a synchronous API was preferred. There was also at least one member voicing strong dissent to that agreement. Members of the TAG were invited to attend the Media WG F2F to give technical feedback on the question, and the feedback given was that a synchronous API made more sense in this particular case.

This question has been very contentious, with strong feelings on both sides. But lack of resolution of this issue is blocking progress on this specification. So I propose the following resolution:

RESOLVED: Both the Document level and the HTMLMediaElement level `autoplayPolicy` APIs should be converted from methods returning a Promise to a simple property. I.e.:

```
partial interface Document {
  readonly attribute AutoplayPolicy autoplayPolicy;
};

partial interface HTMLMediaElement {
  readonly attribute AutoplayPolicy autoplayPolicy;
};
```

This CFC will be open until Friday October 18.

Positive responses are encouraged (e.g. a 👍 on this issue). Silence will be interpreted as implicit support. If you object, please provide a rationale for your objection and let the group know if/how the proposal could be changed to address your objection.

**Comment by robwalch** [comment]
Is there a definition of `AutoplayPolicy` we can refer to? Will it give general information about whether the browser may allow playback with or without audio, leaving you guessing as to whether a call to `.play()` will be rejected with an exception?

**Comment by padenot** [comment]
@robwalch, [this](https://github.com/w3c/autoplay/pull/8/files?short_path=817a23c#diff-817a23c792520ce222813d3eff70d031) is the current draft, where you can see the different values for the `Autoplaypolicy` enum, and various examples and bits of info.

But please ask if you need more context and/or info.

**Comment by robwalch** [comment]
Thanks @padenot,
And we're sure all implementations as synchronous (like a site specific policy based on chrome://media-engagement/)?

**Comment by mounirlamouri** [comment]
Why is the media element attribute being discussed? I thought we all agreed on a solution for this @padenot ?

**Comment by jernoble** [comment]
@mounirlamouri, you pointed at TPAC that all the arguments for making the Document API synchronous applied equally well to the HTMLMediaElement API; I took that feedback to heart.

**Comment by mounirlamouri** [comment]
@jernoble @padenot @jyavenard and I discussed the topic offline and concluded that it would be more constructive to file an official TAG Dispute Resolution asking them to clarify the point of contention which is mostly what is the bar at which point an API should be async.

I will send a link to the issue as soon as it is posted.

**Comment by mounirlamouri** [comment]
The TAG escalation was filed: https://github.com/w3ctag/design-reviews/issues/439

**Comment by gkatsev** [comment]
Hello all, has there been any updates on this? The TAG had reached a decision in december of 2019 https://github.com/w3ctag/design-reviews/issues/439#issuecomment-561902607

It's still a bit of a pain point of player implementers and would be nice to have this be available for usage.

What are the next steps to make progress on this. Add it to the Media WG agenda for the next meeting? Thanks!

**Comment by chrisn** [comment]
@gkatsev See [this discussion](https://github.com/w3c/charter-media-wg/issues/24) in the context of Media WG rechartering. Adding agenda label for next meeting.

**Comment by gkatsev** [comment]
@chrisn thanks! I guess I completely missed that issue.

**Comment by chrisn** [comment]
I think we can close this as we have the TAG resolution, and we're making progress on the spec draft.
