### ISSUE TITLE
Publish FPWD

### ISSUE THREAD

**Issue by chrisn** [w3c/autoplay#26]
The [CfC to publish AutoPlay Policy Detection as FPWD][1] has now closed, with positive responses from Mozilla, Apple, Google, and BBC.

@tidoust Would you mind sending the transition request, and to set up automatic publishing of the draft to /TR?

[1]: https://lists.w3.org/Archives/Public/public-media-wg/2022Mar/0000.html

**Comment by tidoust** [comment]
The [First Public Working Draft of the Autoplay Policy Detection spec](https://www.w3.org/TR/2022/WD-autoplay-detection-20220315/) was published today.

I also prepared a pull request to enable automatic publishing of the draft to /TR from now on, see #28.
