### ISSUE TITLE
Split security and privacy considerations

### ISSUE THREAD

**Issue by chrisn** [w3c/autoplay#29]
The Security and Privacy Considerations section of the spec should be split, as documented in https://w3ctag.github.io/security-questionnaire/#considerations. (We received [similar feedback](https://github.com/w3c/media-capabilities/issues/175) on Media Capabilities).

I also suggest that we write a document with answers to the questionnaire. See the [Media Capabilities document](https://github.com/w3c/media-capabilities/blob/main/security-privacy-questionnaire.md) for a previous example.

**Comment by alastor0325** [comment]
This has been fixed.
