### ISSUE TITLE
Autoplay setting not respected.

### ISSUE THREAD

**Issue by Betsy25** [w3c/autoplay#4]
I have autoplay of media blocked for Youtube, however this is never respected when I click on a video from my YT "Subscriptions" page, it is only respected if I right click the thumbnails & "Open Link in New Tab" or middle-click to do so.

In FF stable, it works fine as it should.

**Comment by mounirlamouri** [comment]
Hi @Betsy25 you may want to file a bug in Chrome (assuming it's a Chrome bug) via http://crbug.com/new
